### ISSUE TITLE
QoL+ Engrams Gone After Update

### ISSUE THREAD

**Issue by DMBarber** [VoidArkMods/QoLPlus#155]
I updated to the latest version this morning and now all QoL+ engrams are gone. I also cannot place any QoL+ object in my base if I convert it in the convertor table.

I posted, and updated, a similar issue earlier, but this is a bit more dire as all engrams are now gone from the list.

Windows 11 PC
Single Player

**Comment by VoidArkMods** [comment]
Hello!
This usually happens when the mod corrupts itself during the upload. You can browse to the QoL+ installation folder (it should look like `C:\Program Files (x86)\Steam\steamapps\common\ARK Survival Ascended\ShooterGame\Binaries\Win64\ShooterGame\Mods\83374\939228_5052743`, adapt if you installed the game somewhere else), and delete the `QoLPlus` folder in it. The game will naturally download it again from CurseForge the next time you start a Single Player game or join a server that has it.

**Comment by DMBarber** [comment]
Thank you. I also, on a whim, moved the mod to the bottom of the load order and that fixed it. I now have my engrams back and can once again place items (except the multi lamp) from my inventory.
