### ISSUE TITLE
Cannot place any items on PS5.

### ISSUE THREAD

**Issue by rajnaimesh007** [VoidArkMods/QoLPlus#59]
Tried small box, large box .. standing torch.
But cannot place them on the foundation or ground.

Uninstalled mod and reinstalled but same result.

**Comment by rajnaimesh007** [comment]
Weird, I can place items on single player but not on a server.

**Comment by rajnaimesh007** [comment]
Ini settings are default on the server except 
The differences are: disabled the ability to FreezeGrowth and BoostGrowth on the Mutator and disabled Chibify Tames on the Gun (it wasn't working when we tested it)

**Comment by rajnaimesh007** [comment]
![18c2533817627-screenshotUrl.jpg](https://github.com/VoidArkMods/QoLPlus/assets/16405313/bb84a02e-bf53-47e7-a351-bb85e8d626ed)

**Comment by rajnaimesh007** [comment]
@VoidArkMods so I see the server I play doesn't have two mods which support cross-platform.

So it can be due to the indexing issue of items ? 
Because I can place items but they are all messed up.
Try to place large box and it places small box from your inventory. (Shown in video I uploaded above)

(Yes consoles do allow you to join the server, even if you have some mods missing, unlike PC)

**Comment by VoidArkMods** [comment]
Hello!
I made several  additional tests on PS5 and everytime I have been able to place structures properly. I witnessed other players being able to place the correct structures on PS5.
It's either a server issue or a client install issue. In order to narrow down the cause, can you try to run a single player session with QoL+ active and see if the issue is present? If it is, then it has to do with your installation of the mod and I'd suggest to uninstall and reinstall it. You can also uninstall it and let the server you try to join install it for you. If the issue cannot be reproduced in single player, then it's probably the server that has a bad install of the mod. If you can reach out to the server admin, they can update the mod manually.

Regards

**Comment by rajnaimesh007** [comment]
Thanks @VoidArkMods , I tested in single player and it work fine. I think you can close this issue.
