### ISSUE TITLE
Doesn't work for controllers

### ISSUE THREAD

**Issue by Hyper3007** [VoidArkMods/QoLPlus#77]
I noticed you added the mod for crossplay, i just put it on my crossplay server but seems to not work with controllers they can open the menu but the curser it gives they cant move it and select items, hope you can fix this as its a really good QoL mod. Just to add this is for the inventory pulling items from the list

**Comment by VoidArkMods** [comment]
Hello!
I bought an Xbox and a PS5 last week in order to test the crossplay and I'm confident all UIs do work with a controller. The virtual cursor is able to click on the pulling overlay, the select box from hitching posts/omnitool, select creatures in the feeding through configuration etc.
Are you sure the mod has been installed properly? I'm following closely the crossplay compatibility on all supported platforms and all of them are working with the current version of the mod.

**Comment by Hyper3007** [comment]
i dont have console just going by what people are telling on the server, thanks for the reply and does the mod need to be in any order ? as right now its bottom of the list on my server, should i move it up to near the top ?

**Comment by Hyper3007** [comment]
Ok thats fine, thanks for the reply, this is what the person said to me happens. 

(Actually, I don't think we get the curser on this menu with controller, and can't select items in the lists, the selection  just toggles between the main buttons on the bottom and right)

My reply
(So you can’t move that  curser with your analog sticks ?)

(Yeah 100%, as soon as I move my joystick the curser dissapears, I wiggle my mouse and it comes back)

However someone on PS5 said it works, so maybe its the mouse the person is using as well.

**Comment by Hyper3007** [comment]
So i just had other people test it, both on PS5 and Xbox and they saying its all working, you can close this issue if you would like as seems like its got something to do with the other person install of the mod or the mouse they are using. Thanks again for the help, keep up the great work.
